name: Flutter CI/CD

on:
  push:
    tags:
      - 'v*'  # Trigger when pushing a version tag like v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_DISABLE_WATCHER: true
      FLUTTER_DISABLE_ANALYTICS: true

    strategy:
      matrix:
        platform: [android]  # Add 'ios' later if you use macOS runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Android APK
        if: matrix.platform == 'android'
        run: flutter build apk --release

      # --- future iOS build ---
      # - name: Build iOS App
      #   if: matrix.platform == 'ios'
      #   run: flutter build ios --release

      - name: Upload release APK to GitHub
        if: matrix.platform == 'android'
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
